-- MySQL Script generated by MySQL Workbench
-- Wed Nov  3 16:59:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id` INT NOT NULL,
  `full_Name` VARCHAR(90) NOT NULL,
  `contacts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `planning_date_end` VARCHAR(45) NOT NULL,
  `date_end` VARCHAR(45) NULL,
  `price` INT NOT NULL,
  `date_begin` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Orders_Clients_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`Clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouses` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type_of_warehouse` VARCHAR(45) NOT NULL,
  `amount_of_free_space` INT NOT NULL,
  `warehous_location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specifications` (
  `id` INT NOT NULL,
  `name_product` VARCHAR(45) NOT NULL,
  `discription` TEXT NOT NULL,
  `number_of_production_stages` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_Composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_Composition` (
  `id` INT NOT NULL,
  `final_quantity` INT NOT NULL,
  `description` TEXT NULL,
  `orders_id` INT NOT NULL,
  `specifications_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Composition_Orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_Order_Composition_Specifications1_idx` (`specifications_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Composition_Orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Composition_Specifications1`
    FOREIGN KEY (`specifications_id`)
    REFERENCES `mydb`.`Specifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statuses_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statuses_Product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Final_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Final_Products` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `warehouses_id` INT NOT NULL,
  `production_stage_number` INT NULL,
  `order_Composition_id` INT NOT NULL,
  `statuses_Product_id` INT NOT NULL,
  `specifications_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Final_Products_Warehouses1_idx` (`warehouses_id` ASC) VISIBLE,
  INDEX `fk_Final_Products_Order_Composition1_idx` (`order_Composition_id` ASC) VISIBLE,
  INDEX `fk_Final_Products_Statuses_Product1_idx` (`statuses_Product_id` ASC) VISIBLE,
  INDEX `fk_Final_Products_Specifications1_idx` (`specifications_id` ASC) VISIBLE,
  CONSTRAINT `fk_Final_Products_Warehouses1`
    FOREIGN KEY (`warehouses_id`)
    REFERENCES `mydb`.`Warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Final_Products_Order_Composition1`
    FOREIGN KEY (`order_Composition_id`)
    REFERENCES `mydb`.`Order_Composition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Final_Products_Statuses_Product1`
    FOREIGN KEY (`statuses_Product_id`)
    REFERENCES `mydb`.`Statuses_Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Final_Products_Specifications1`
    FOREIGN KEY (`specifications_id`)
    REFERENCES `mydb`.`Specifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materials` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(90) NOT NULL,
  `price` INT NOT NULL,
  `status_material` VARCHAR(45) NOT NULL,
  `renewal_method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Printers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Printers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `power` INT NOT NULL,
  `occupancy` TINYINT NOT NULL,
  `description` VARCHAR(255) NULL,
  `max_printing_time` INT NULL,
  `time_stopping` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Finding_Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Finding_Materials` (
  `material_id` INT NOT NULL,
  `warehous_id` INT NOT NULL,
  `quantity_material` INT NOT NULL,
  PRIMARY KEY (`material_id`, `warehous_id`),
  INDEX `fk_Materials_has_Warehouses_Warehouses1_idx` (`warehous_id` ASC) VISIBLE,
  INDEX `fk_Materials_has_Warehouses_Materials1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_Materials_has_Warehouses_Materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mydb`.`Materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_has_Warehouses_Warehouses1`
    FOREIGN KEY (`warehous_id`)
    REFERENCES `mydb`.`Warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specification_Composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specification_Composition` (
  `id` INT NOT NULL,
  `specifications_id` INT NOT NULL,
  `materials_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Specification_Composition_Specifications1_idx` (`specifications_id` ASC) VISIBLE,
  INDEX `fk_Specification_Composition_Materials1_idx` (`materials_id` ASC) VISIBLE,
  CONSTRAINT `fk_Specification_Composition_Specifications1`
    FOREIGN KEY (`specifications_id`)
    REFERENCES `mydb`.`Specifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specification_Composition_Materials1`
    FOREIGN KEY (`materials_id`)
    REFERENCES `mydb`.`Materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Production_Stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Production_Stages` (
  `id` INT NOT NULL,
  `specifications_id` INT NOT NULL,
  `execution_time` INT NOT NULL,
  `printers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `specifications_id`),
  INDEX `fk_Prosuction_Stages_Specifications1_idx` (`specifications_id` ASC) VISIBLE,
  INDEX `fk_Prosuction_Stages_Printers1_idx` (`printers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Prosuction_Stages_Specifications1`
    FOREIGN KEY (`specifications_id`)
    REFERENCES `mydb`.`Specifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prosuction_Stages_Printers1`
    FOREIGN KEY (`printers_id`)
    REFERENCES `mydb`.`Printers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resources_Used`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Resources_Used` (
  `specification_Composition_id` INT NOT NULL,
  `production_Stages_id` INT NOT NULL,
  `quantity_resources_used` INT NOT NULL,
  PRIMARY KEY (`specification_Composition_id`, `production_Stages_id`),
  INDEX `fk_Specification_Composition_has_Prosuction_Stages_Prosucti_idx` (`production_Stages_id` ASC) VISIBLE,
  INDEX `fk_Specification_Composition_has_Prosuction_Stages_Specific_idx` (`specification_Composition_id` ASC) VISIBLE,
  CONSTRAINT `fk_Specification_Composition_has_Prosuction_Stages_Specificat1`
    FOREIGN KEY (`specification_Composition_id`)
    REFERENCES `mydb`.`Specification_Composition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specification_Composition_has_Prosuction_Stages_Prosuction1`
    FOREIGN KEY (`production_Stages_id`)
    REFERENCES `mydb`.`Production_Stages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
